language: cpp
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./myinstall_1 -DCMAKE_BUILD_TYPE=Debug
script: 
  - make help && make && make test 
  - ls
  - make install
  - ls
  - make package
  - ls
  - ctest -D Experimental
  - ls -al