language: cpp
before_script:
  - sudo apt-get -qq install valgrind
script: 
  - which valgrind
  - mkdir _build_one
  - cd _build_one
  - cmake ../one -DMEMORYCHECK_COMMAND:FILEPATH=/home/kitware/local/bin/valgrind
  - make help
  - make
  - make test
  - ls
  - ./OneExe
  - ctest -D Experimental
# compiler:
  # - gcc
# before_script:
  # - mkdir build
  # - cd build
  # - cmake .. -DCMAKE_INSTALL_PREFIX=./myinstall_1 -DCMAKE_BUILD_TYPE=Debug
# script: 
  # - make help && make && make test 
  # - ls
  # - make install
  # - ls
  # - make package
  # - ls
  # - ctest -D Experimental
  # - ls -al