language: cpp
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./myinstall_1
script: 
  - make help && make && make test 
  - ls
  - make install
  - ls